apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-env-els-data
spec:
  storageClassName: elastic-env-els-data
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /opt/kickstart-elk/elasticsearch/data
  volumeBindingMode: WaitForFirstConsumer
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
              - linux
          - key: node-role.kubernetes.io/worker
            operator: In
            values:
              - worker
          - key: type
            operator: In
            values:
              - on-premise
          - key: provider
            operator: In
            values:
              - host
          - key: service
            operator: In
            values:
              - virtualbox
          - key: region
            operator: In
            values:
              - local
          - key: availability_zone
            operator: In
            values:
              - local-c
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-env-els-log
spec:
  storageClassName: elastic-env-els-log
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/kickstart-elk/elasticsearch/log
  volumeBindingMode: WaitForFirstConsumer
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
              - linux
          - key: node-role.kubernetes.io/worker
            operator: In
            values:
              - worker
          - key: type
            operator: In
            values:
              - on-premise
          - key: provider
            operator: In
            values:
              - host
          - key: service
            operator: In
            values:
              - virtualbox
          - key: region
            operator: In
            values:
              - local
          - key: availability_zone
            operator: In
            values:
              - local-c
